// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMkwhIjHAPHo9r2dIBtwzgXgBvJPrhP4w',
    appId: '1:993200032041:web:f38d1b9b7ce1af15a54f38',
    messagingSenderId: '993200032041',
    projectId: 'nuli-todolist',
    authDomain: 'nuli-todolist.firebaseapp.com',
    databaseURL: 'https://nuli-todolist-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nuli-todolist.appspot.com',
    measurementId: 'G-ENF7RTEQDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrKV5bwI2V8N2dgwN94hRBfEKczs0WjoY',
    appId: '1:993200032041:android:35dc9fc307414527a54f38',
    messagingSenderId: '993200032041',
    projectId: 'nuli-todolist',
    databaseURL: 'https://nuli-todolist-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nuli-todolist.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCFx6CeUKWfAfiggzkJsZCaTW2h5L74h0',
    appId: '1:993200032041:ios:f69d923481bfeb1aa54f38',
    messagingSenderId: '993200032041',
    projectId: 'nuli-todolist',
    databaseURL: 'https://nuli-todolist-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nuli-todolist.appspot.com',
    iosClientId: '993200032041-l4mpbl90i8td727ogrnvij94ivl24n81.apps.googleusercontent.com',
    iosBundleId: 'id.ac.petra.nuli',
  );
}
